version: 2

sources:
  - name: raw
    database: PLANETKART_DATABASE
    schema: PLANETKART_RAW
    tables:
      - name: customers
      - name: vw_orders
        loaded_at_field: order_date_cast
        config:
          freshness:
            error_after:
              count: 2
              period: day
      - name: order_items
      - name: products
      - name: regions


models:
  - name: stg_customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: region_id
        tests:
          - accepted_values:
              values: ['R001', 'R002', 'R003', 'R004']

  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: order_date
        tests:
          - not_null
      - name: status
        tests:
          - accepted_values:
              values: ['Completed', 'Pending', 'Shipped', 'Cancelled']
